{
  perSystem = { pkgs, system, ... }: {
    # Same derivation as the karakeep NixOS service uses (services.karakeep.package).
    # Exposed so CI can pre-build/cache it for alma (aarch64).
    # Mirror the system config's nixpkgs.config (modules/system/nix.nix) so the
    # pnpm-9.15.9 pin used by karakeep's build is permitted.
    packages.karakeep =
      let
        pkgsK = import pkgs.path {
          inherit system;
          config = {
            allowUnfree = true;
            permittedInsecurePackages = [ "pnpm-9.15.9" ];
          };
        };
      in
      pkgsK.karakeep;
  };

  flake.nixosModules.karakeep = { config, lib, ... }: {
    sops.secrets.karakeep_environment_file = {
      sopsFile = ../../secrets/alma.yaml;
    };

    services = {
      oink.domains = [
        {
          domain = "${config.systemConstants.domain_name}";
          subdomain = "karakeep";
        }
      ];

      # Workaround: the upstream NixOS meilisearch module sets
      # experimental_dumpless_upgrade = true by default, but meilisearch 1.51.0
      # dropped that TOML field in favour of `upgrade_db`. Override the
      # entire settings to swap the option name while keeping all other defaults.
      meilisearch.settings = lib.mkForce {
        db_path = "/var/lib/meilisearch";
        dump_dir = "/var/lib/meilisearch/dumps";
        snapshot_dir = "/var/lib/meilisearch/snapshots";
        no_analytics = true;
        http_addr = "localhost:7700";
        upgrade_db = true;
      };

      karakeep = {
        enable = true;
        meilisearch.enable = true;
        browser.enable = true;
        environmentFile = config.sops.secrets.karakeep_environment_file.path;
        extraEnvironment = {
          NEXTAUTH_URL = "https://karakeep.${config.systemConstants.domain_name}";
          DISABLE_PASSWORD_AUTH = "true";
          OAUTH_WELLKNOWN_URL = "https://id.${config.systemConstants.domain_name}/.well-known/openid-configuration";
          OAUTH_CLIENT_ID = "karakeep";
          OAUTH_PROVIDER_NAME = "Pocket ID";
          OAUTH_SCOPE = "openid email profile";
          OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING = "true";
          PORT = "3003";
          CRAWLER_FULL_PAGE_SCREENSHOT = "true";
          CRAWLER_FULL_PAGE_ARCHIVE = "true";
          DISABLE_SIGNUPS = "true";
          DISABLE_NEW_RELEASE_CHECK = "true";
        };
      };

      nginx.virtualHosts."karakeep.${config.systemConstants.domain_name}" = {
        enableACME = true;
        forceSSL = true;
        locations."/" = {
          proxyPass = "http://127.0.0.1:3003";
        };
      };
    };

    systemd =
      let
        # Single source of truth for where Karakeep keeps its live data.
        dataDir = "/mnt/filen/Alma/services/karakeep";
      in
      {
        services = {
          karakeep-web = {
            environment.DATA_DIR = lib.mkForce dataDir;
            serviceConfig.EnvironmentFile = lib.mkAfter [
              "/var/lib/oidc-client-secrets/karakeep-env"
            ];
            after = [ "pocket-id-seed.service" ];
            requires = [ "pocket-id-seed.service" ];
          };
          karakeep-workers.environment.DATA_DIR = lib.mkForce dataDir;

          # The upstream NixOS module runs the schema migrator (karakeep-init)
          # against its own StateDirectory (/var/lib/karakeep), but web/workers are
          # pointed at ${dataDir}. That left the *live* DB stuck on an old schema
          # (missing importSessions.completedAt / user.manualTierName), which broke
          # archiving/import. Keep secret generation in the StateDirectory, but run
          # migrations against the same DATA_DIR the services actually use.
          karakeep-init.script = lib.mkForce ''
            umask 0077

            if [ ! -f "$STATE_DIRECTORY/settings.env" ]; then
              cat <<EOF >"$STATE_DIRECTORY/settings.env"
            # Generated by NixOS Karakeep module
            MEILI_MASTER_KEY=$(openssl rand -base64 36)
            NEXTAUTH_SECRET=$(openssl rand -base64 36)
            EOF
            fi

            export DATA_DIR="${dataDir}"
            exec "${config.services.karakeep.package}/lib/karakeep/migrate"
          '';
        };

        tmpfiles.rules = [ "d ${dataDir} 0755 root root -" ];
      };
  };
}
